
export const KafkaTopics = {
  USER_REQUESTS: 'user-requests',       // Requests like update/delete (from auth)
  USER_EVENTS: 'user-events',           // Confirmations like USER_UPDATED

  PROPERTY_REQUESTS: 'property-requests',
  PROPERTY_EVENTS: 'property-events',

  BOOKING_REQUESTS: 'booking-requests',
  BOOKING_EVENTS: 'booking-events',

  PAYMENT_REQUESTS: 'payment-requests',
  PAYMENT_EVENTS: 'payment-events',

  NOTIFICATION_EVENTS: 'notification-events',
} as const;

export type KafkaTopic = typeof KafkaTopics[keyof typeof KafkaTopics];

export const EventTypes = {
  // User
  USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETE_REQUEST: 'USER_DELETE_REQUEST',
  USER_DELETED: 'USER_DELETED',
  USER_CREATE_REQUEST: 'USER_CREATE',

  // Property
  PROPERTY_CREATE_REQUEST: 'PROPERTY_CREATE_REQUEST',
  PROPERTY_CREATED: 'PROPERTY_CREATED',
  PROPERTY_UPDATE_REQUEST: 'PROPERTY_UPDATE_REQUEST',
  PROPERTY_UPDATED: 'PROPERTY_UPDATED',
  PROPERTY_DELETE_REQUEST: 'PROPERTY_DELETE_REQUEST',
  PROPERTY_DELETED: 'PROPERTY_DELETED',

  // Booking
  BOOKING_CREATE_REQUEST: 'BOOKING_CREATE_REQUEST',
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CANCEL_REQUEST: 'BOOKING_CANCEL_REQUEST',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',

  // Payment
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_REFUND: 'PAYMENT_REFUND',

  // Notifications
  NOTIFY_USER: 'NOTIFY_USER',
  NOTIFY_HOST: 'NOTIFY_HOST',
} as const;
